### ISSUE TITLE
time settings do only show sometimes

### ISSUE THREAD

**Issue by Danfro** [kugiigi/indicator-darkmode#1]
When activating "Auto switch", the options to set the times are only shown right after the app has been started. A bit later those settings are not shown.

They are always shown when the switch is activated.

Please see the log: http://paste.ubuntu.com/p/tW6vy7zpb7/ and here http://paste.ubuntu.com/p/PjcT2c8j9N/.

**Comment by kugiigi** [comment]
This is weird. I don't get this errors. Have you perhaps installed a previous version or something?
The looks like an error during my development which I think I've fixed already. I can't replicate this on my MX4 and Nexus 5.

**Comment by Danfro** [comment]
OpenStore version. Never had another one running.

On Wed, 17 Jun 2020 21:38:11 -0700, Kugi Eusebio wrote:
> This is weird. I don't get this errors. Have you perhaps 
> installed a previous version or something?
> The looks like an error during my development which I think 
> I've fixed already. I can't replicate this on my MX4 and Nexus 
> 5.
>

--

**Comment by Danfro** [comment]
Same here. Not reproducible anymore with the new version. Call it done too.
