### ISSUE TITLE
time not fully localized

### ISSUE THREAD

**Issue by Danfro** [kugiigi/indicator-darkmode#4]
The time in the app is shown in am/pm. But the time picker gives local 24h times.

![screenshot](https://user-images.githubusercontent.com/37637312/84978002-1d82a500-b12c-11ea-89f2-5b8621cd31a9.jpg)

**Comment by kugiigi** [comment]
I don't think the `DataPicker` component supports formating/localization. Even the clock app has this problem. If someones knows a way, please let me know 😄

**Comment by Danfro** [comment]
Well, I am using a 24h locale. So in my case the times shown in the app are "wrong". 😉

On Wed, 17 Jun 2020 21:49:41 -0700, Kugi Eusebio wrote:
> I don't think the `DataPicker` component supports 
> formating/localization. Even the clock app has this problem. If 
> someones knows a way, please let me know 😄
> 


--
